### ISSUE TITLE
Getting error in running the sample file

### ISSUE THREAD

**Issue by ghost** [alberto-martin/googlescholar#1]
Hi,

I am getting an error while running your sample file. Please guide me how can I resolve the issue?

![1](https://user-images.githubusercontent.com/734469/50686400-527d6380-102e-11e9-86c7-4dd6df9fdc45.PNG)

Sample file:  [url2.txt](https://github.com/alberto-martin/googlescholar/files/2726811/url2.txt)

**Comment by alberto-martin** [comment]
Hi! It seems that the "html" variable does not contain a string of characters, but a byte sequence, which the write() function can't write to a file. My guess is that you might be using Python 3, instead of Python 2. Unfortunately, this code is written for Python 2, so you may have to modify it to work with Python 3, or run it on an environment with Python 2 installed.

**Comment by ghost** [comment]
Thanks for your answer...
It is resolved now b using Python 2.7
